name: mac

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4

      - name: Configure macOS Desktop & Screen Sharing
        run: |
          sudo mdutil -i off -a

                  # Set password for runner
          echo "${{ secrets.VNC_USER_PASSWORD }}" | sudo passwd -u runner

          # Enable Apple Remote Desktop / VNC
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users runner -privs -all -restart -agent -menu
          # Configure legacy VNC authentication
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvncpw -vncpw "${{ secrets.VNC_PASSWORD }}"

          # Start UI session awake
          sudo caffeinate -dimsu -w $$ &
      - name: Connect Mac to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Show Tailscale Address
        run: |
          echo "=========================================="
          echo "Tailscale IPv4 address:"
          tailscale ip -4
          echo "=========================================="
          tailscale status

      - name: Keep Alive
        run: |
          echo "=========================================="
          echo "macOS GUI desktop is initialized and running"
          echo "=========================================="

          while true; do
            echo "----- $(date) -----"
            echo "Tailscale status:"
            tailscale status
            echo "VNC port:"
            nc -zv 127.0.0.1 5900
            echo "Keeping runner alive..."
            sleep 60
          done
